const DEFAULT_TODO_RECORDS_PAGE_SIZE = 3;
const DEFAULT_TODO_ORDERING_DIRECTION = "DESC";
const DEFAULT_TODO_ORDERING_FIELD = "user_name";

export {
  DEFAULT_TODO_RECORDS_PAGE_SIZE,
  DEFAULT_TODO_ORDERING_DIRECTION,
  DEFAULT_TODO_ORDERING_FIELD,
};
